### ISSUE TITLE
Post-publish checklist

### ISSUE THREAD

**Issue by phansch** [phansch/phansch.github.com#81]
* [ ]  Post on twitter
* [ ]  Submit to http://www.rubyflow.com/#submitform
* [ ] Post to http://reddit.com/r/ruby in the evening (not on the weekend)
* [ ] Cross-post to dev.to
