### ISSUE TITLE
Rails 4 to 5 migration checklist

### ISSUE THREAD

**Issue by phansch** [phansch/phansch.github.com#85]
* [ ]  [rails-controller-testing](https://github.com/rails/rails-controller-testing)
* [ ]  Use ApplicationRecord instead of ActiveRecord::Base
* [ ]  Migrate to strong parameters (lots of work potentially, need good tests for update and create actions)
